services:
  app:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      TEACHER_CODE: ${TEACHER_CODE}
      TASK_SEND_TIME: ${TASK_SEND_TIME}
    volumes:
      - ./storage:/app/storage
    ports:
      - "8080:8080"
